function C = B5_UQLab_Reliability_Skeleton_CORRECTED(modelFile)
% Carrega o contrato; CV e condicional ao conjunto de variaveis selecionado.
% CV nao e validacao externa da selecao nem do pipeline completo.
assert(isfile(modelFile), 'B5:ModelFile', 'Arquivo do Stage 3 nao encontrado.');
assert(~isempty(which('uqlab')), 'B5:UQLab', 'UQLab nao encontrado.');
uqlab('-nosplash');
S = load(modelFile, 'modelPCK','vars_train','muX','sdX','muY','sdY', ...
    'muX_original','sdX_original','muY_original','sdY_original', ...
    'sampleID','Perf','Stage3Contract');
assert(isfield(S,'modelPCK') && isfield(S,'vars_train') && ...
    isfield(S,'Stage3Contract'), 'B5:Contract', 'Modelo ou contrato ausente.');
K = S.Stage3Contract;
assert(isstruct(K) && isscalar(K) && ...
    isfield(K,'model_input_representation') && ...
    strcmp(K.model_input_representation,'standardized'), 'B5:Contract', ...
    'Stage3Contract.model_input_representation deve ser standardized.');
assert(isfield(K,'input_normalization') && ...
    strcmp(K.input_normalization,'standardization'), 'B5:Contract', ...
    'Stage3Contract.input_normalization deve ser standardization.');
assert(isfield(K,'external_input_transform') && ...
    strcmp(K.external_input_transform,'(X - muX) ./ sdX'), 'B5:Contract', ...
    'Transformacao externa de entradas ausente ou incompativel.');
assert(isfield(K,'lim_m'), 'B5:Contract', 'Limite em metros ausente.');
validateattributes(K.lim_m, {'numeric'}, {'real','scalar','finite','positive'});
C.names = B5_Utils_CORRECTED.ValidateNames(S.vars_train, 'vars_train');
C.normalization = B5_Utils_CORRECTED.Normalization(S);
assert(numel(C.names) == numel(C.normalization.muX), 'B5:Contract', ...
    'Nomes e estatisticas de normalizacao incompatíveis.');
if isfield(K,'input_names')
    contractNames = B5_Utils_CORRECTED.ValidateNames(K.input_names, 'input_names');
    assert(isequal(C.names,contractNames), 'B5:Contract', ...
        'Ordem das variaveis difere do contrato.');
end
assert(isfield(S,'sampleID'), 'B5:IDs', 'IDs do treinamento ausentes.');
C.trainingIDs = B5_Utils_CORRECTED.ValidateIDs(S.sampleID, 'Stage3.sampleID');
assert(isfield(S,'Perf') && istable(S.Perf) && height(S.Perf) == 1 && ...
    all(ismember({'R2_CV','LOO'}, S.Perf.Properties.VariableNames)), ...
    'B5:CV', 'Metricas CV/LOO do Stage 3 ausentes.');
validateattributes(S.Perf.R2_CV, {'numeric'}, {'real','scalar','finite'});
validateattributes(S.Perf.LOO, {'numeric'}, {'real','scalar','finite','nonnegative'});
assert(S.Perf.R2_CV >= 0.5, 'B5:CV', ...
    'R2_CV < 0.5; modelo rejeitado para analise de confiabilidade.');
C.CV = S.Perf;
C.cv_scope = 'conditional_on_selected_variables';
C.modelPCK = S.modelPCK;
C.limit_m = double(K.lim_m);
C.Stage3Contract = K;
C.predict = @(X) B5_Predict_PCK_CORRECTED(C.modelPCK, X, ...
    C.normalization.muX, C.normalization.sdX, ...
    C.normalization.muY, C.normalization.sdY);
end
